name: PluginTutorial
version: '${project.version}'
main: me.supersilverstone.plugintutorial.PluginTutorial
api-version: 1.19
commands:
  feed:
    description: Feed yourself all of the way!
    usage: /<command>
